$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    autoplay:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:4
        }
    }
});
document.getElementById("menu").onclick = function(){
    document.getElementById("menu_wrapper").classList.toggle("show");
}
